server:
  port: 9090

spring:
  datasource:
    password: "123456"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/library-management?serverTimezone=GMT%2b8
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true  # 开启数据库字段下划线转驼峰
